# Generated by Django 5.2.17 on 2026-10-08 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEstabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=120)),
                ('horario_funcionamento', models.CharField(blank=True, default='', max_length=120)),
                ('endereco', models.CharField(blank=True, default='', max_length=255)),
                ('limite_gastos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Margem máxima de gastos')),
            ],
        ),
    ]
