# Generated by Django 5.2.17 on 2026-10-08 16:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_alter_produto_quantidade'),
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venda_itens', to='catalogo.item')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='venda.venda')),
            ],
        ),
    ]
