# Generated by Django 5.2.17 on 2026-10-01 22:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0002_produto_despesas_variaveis_percentual_and_more'),
        ('servico', '0002_servico_custo_direto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('credito', 'Cartão de crédito'), ('debito', 'Cartão de débito'), ('pix', 'Pix')], max_length=10)),
                ('telefone_whatsapp', models.CharField(blank=True, max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('troco', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ('-criada_em', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('produto', 'Produto'), ('servico', 'Serviço')], max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_vendidos', to='produto.produto')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_vendidos', to='servico.servico')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='venda.venda')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
