# Generated by Django 5.2.17 on 2026-10-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEstabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=120)),
                ('horario_funcionamento', models.CharField(blank=True, default='', max_length=120)),
                ('endereco', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='venda',
            name='endereco_estabelecimento',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='venda',
            name='horario_funcionamento',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='venda',
            name='nome_cliente',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='venda',
            name='nome_estabelecimento',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
