# Generated by Django 5.2.17 on 2026-10-05 03:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_dadosestabelecimento_venda_endereco_estabelecimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('credito', 'Cartão de crédito'), ('debito', 'Cartão de débito'), ('pix', 'Pix')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('troco', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='venda.venda')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
