# Generated by Django 5.2.17 on 2026-10-01 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servico', '0002_servico_custo_direto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('servicos', models.ManyToManyField(blank=True, related_name='agendamentos', to='servico.servico')),
            ],
            options={
                'ordering': ('data', 'nome', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HorarioAgendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='agenda.agendamento')),
            ],
            options={
                'ordering': ('inicio',),
                'constraints': [models.UniqueConstraint(fields=('data', 'inicio'), name='agenda_horario_data_inicio_unico')],
            },
        ),
    ]
