# Generated by Django 5.2.17 on 2026-10-02 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('conta_pagar', '0002_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='descricao_agendar_para',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='conta_pagar.funcionario'),
        ),
    ]
